services:
  solr:
    container_name: solr
    image: solr:8.11.1
    command:
      - solr-precreate
      - search
    ports:
     - '8983:8983'
    volumes:
      - ./data:/var/solr/data
  cors: 
    image: nginx:alpine
    ports:
      - 8899:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
